<a href="https://colab.research.google.com/github/CRosero/aml-project/blob/master/train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Mount Google Drive
from google.colab import drive
drive.mount('/gdrive/')

Mounted at /gdrive/


In [2]:
# Clone the entire repo.
!git clone -l -s git://github.com/CRosero/aml-project.git cloned-repo
%cd cloned-repo
!ls

Cloning into 'cloned-repo'...
remote: Enumerating objects: 85, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 85 (delta 21), reused 0 (delta 0), pack-reused 49
Receiving objects: 100% (85/85), 53.81 KiB | 1.05 MiB/s, done.
Resolving deltas: 100% (43/43), done.
/content/cloned-repo
dataset     eval.py  model	train.ipynb  utils.py
eval.ipynb  loss.py  README.md	train.py


In [3]:
!pip install tensorboardX

     |████████████████████████████████| 124 kB 5.3 MB/s 


In [4]:
import argparse
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from model.build_BiSeNet import BiSeNet
import torch
from tensorboardX import SummaryWriter
from tqdm import tqdm
import numpy as np
from utils import poly_lr_scheduler
from utils import reverse_one_hot, compute_global_accuracy, fast_hist, per_class_iu
from loss import DiceLoss
import torch.cuda.amp as amp
import os
import os.path as osp
import random
import matplotlib.pyplot as plt
import collections
import torchvision
from torchvision.transforms import InterpolationMode
from torch.utils import data
from PIL import Image
import json

In [5]:
def label_mapping(input, mapping):
    output = np.copy(input)
    for ind in range(len(mapping)):
        output[input == mapping[ind][0]] = mapping[ind][1]
    return np.array(output, dtype=np.int64)

In [6]:
class cityscapesDataSet(data.Dataset):
    def __init__(self, root, list_path, max_iters=None, crop_size=(321, 321), mean=(128, 128, 128), scale=True, mirror=True, ignore_label=255):
        self.root = root
        self.list_path = list_path
        self.crop_size = crop_size
        self.scale = scale
        self.ignore_label = ignore_label
        self.mean = mean
        self.is_mirror = mirror
        # self.mean_bgr = np.array([104.00698793, 116.66876762, 122.67891434])
        self.img_ids = [i_id.strip() for i_id in open(list_path)]
        if not max_iters==None:
            self.img_ids = self.img_ids * int(np.ceil(float(max_iters) / len(self.img_ids)))
        self.files = []
        # for split in ["train", "trainval", "val"]:
        for name in self.img_ids:
            # Replace 'train' folder with 'images' folder and  
            # remove reference to city folder for images provided subset of the dataset
            img_file = osp.join(self.root[0].replace('train', 'images'), name.split("/", 1)[1])
            # Replace 'train' folder with 'labels' folder and  
            # remove reference to city folder for images provided subset of the dataset
            # rename file to be that of the label
            label_file = osp.join(self.root[0].replace('train', 'labels'), 
                                  name.split("/", 1)[1].replace('leftImg8bit', 'gtFine_labelIds'))
            self.files.append({
                "img": img_file,
                "label":label_file,
                "name": name
            })
        with open('/gdrive/MyDrive/data/Cityscapes/info.json', 'r') as fp:
            info = json.load(fp)
        self.mapping = np.array(info['label2train'], dtype=np.int)



    def __len__(self):
        return len(self.files)


    def __getitem__(self, index):
        datafiles = self.files[index]
        
        image = Image.open(datafiles["img"]).convert('RGB')
        label = Image.open(datafiles["label"])
        name = datafiles["name"]

        # resize
        print(f'image before resize: {image}')
        image = image.resize(self.crop_size, Image.BILINEAR)
        print(f'image after resize: {image}')
        print(f'label before resize: {label}')
        label = label.resize(self.crop_size, Image.NEAREST)
        print(f'label after resize: {label}')
        image = np.asarray(image, np.float32)
        print(f'image as array: {image}')
        label = np.asarray(label, np.float32)
        print(f'label as array: {label}')
        label = label_mapping(label, self.mapping)
        print(f'label after mapping: {label}')
        

        # re-assign labels to match the format of Cityscapes
        #label_copy = 255 * np.ones(label.shape, dtype=np.float32)
        #for k, v in self.id_to_trainid.items():
        #   label_copy[label == k] = v

        size = image.shape
        image = image[:, :, ::-1]  # change to BGR
        image -= self.mean
        image = image.transpose((2, 0, 1))

        return image.copy(), label.copy()


In [7]:
img_ids = [i_id.strip() for i_id in open('/gdrive/MyDrive/data/Cityscapes/train.txt')]
print(img_ids)

['strasbourg/strasbourg_000000_017593_leftImg8bit.png', 'zurich/zurich_000066_000019_leftImg8bit.png', 'hanover/hanover_000000_032681_leftImg8bit.png', 'ulm/ulm_000066_000019_leftImg8bit.png', 'dusseldorf/dusseldorf_000006_000019_leftImg8bit.png', 'hamburg/hamburg_000000_068916_leftImg8bit.png', 'hamburg/hamburg_000000_095561_leftImg8bit.png', 'monchengladbach/monchengladbach_000000_035364_leftImg8bit.png', 'weimar/weimar_000089_000019_leftImg8bit.png', 'aachen/aachen_000158_000019_leftImg8bit.png']


In [8]:
def val(args, model, dataloader):
    print('start val!')
    # label_info = get_label_info(csv_path)
    with torch.no_grad():
        model.eval()
        precision_record = []
        hist = np.zeros((args.num_classes, args.num_classes))
        for i, (data, label) in enumerate(dataloader):
            label = label.type(torch.LongTensor)
            data = data.cuda()
            label = label.long().cuda()

            # get RGB predict image
            predict = model(data).squeeze()
            predict = reverse_one_hot(predict)
            predict = np.array(predict.cpu())

            # get RGB label image
            label = label.squeeze()
            if args.loss == 'dice':
                label = reverse_one_hot(label)
            label = np.array(label.cpu())

            # compute per pixel accuracy
            precision = compute_global_accuracy(predict, label)
            hist += fast_hist(label.flatten(), predict.flatten(), args.num_classes)

            # there is no need to transform the one-hot array to visual RGB array
            # predict = colour_code_segmentation(np.array(predict), label_info)
            # label = colour_code_segmentation(np.array(label), label_info)
            precision_record.append(precision)
        
        precision = np.mean(precision_record)
        # miou = np.mean(per_class_iu(hist))
        miou_list = per_class_iu(hist)[:-1]
        # miou_dict, miou = cal_miou(miou_list, csv_path)
        miou = np.mean(miou_list)
        print('precision per pixel for test: %.3f' % precision)
        print('mIoU for validation: %.3f' % miou)
        # miou_str = ''
        # for key in miou_dict:
        #     miou_str += '{}:{},\n'.format(key, miou_dict[key])
        # print('mIoU for each class:')
        # print(miou_str)
        return precision, miou

In [9]:
def train(args, model, optimizer, dataloader_train, dataloader_val):
    writer = SummaryWriter(comment=''.format(args.optimizer, args.context_path))

    scaler = amp.GradScaler()

    if args.loss == 'dice':
        loss_func = DiceLoss()
    elif args.loss == 'crossentropy':
        loss_func = torch.nn.CrossEntropyLoss(ignore_index=255)
    max_miou = 0
    step = 0
    for epoch in range(args.num_epochs):
        lr = poly_lr_scheduler(optimizer, args.learning_rate, iter=epoch, max_iter=args.num_epochs)
        model.train()
        tq = tqdm(total=len(dataloader_train) * args.batch_size)
        tq.set_description('epoch %d, lr %f' % (epoch, lr))
        loss_record = []
        for i, (data, label) in enumerate(dataloader_train):
            print(f'data: {data}')
            print(f'label: {label}')
            data = data.cuda()
            label = label.long().cuda()
            optimizer.zero_grad()
            
            with amp.autocast():
                output, output_sup1, output_sup2 = model(data)
                loss1 = loss_func(output, label)
                loss2 = loss_func(output_sup1, label)
                loss3 = loss_func(output_sup2, label)
                loss = loss1 + loss2 + loss3
            
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            
            tq.update(args.batch_size)
            tq.set_postfix(loss='%.6f' % loss)
            step += 1
            writer.add_scalar('loss_step', loss, step)
            loss_record.append(loss.item())
        tq.close()
        loss_train_mean = np.mean(loss_record)
        writer.add_scalar('epoch/loss_epoch_train', float(loss_train_mean), epoch)
        print('loss for train : %f' % (loss_train_mean))
        if epoch % args.checkpoint_step == 0 and epoch != 0:
            import os
            if not os.path.isdir(args.save_model_path):
                os.mkdir(args.save_model_path)
            torch.save(model.module.state_dict(),
                       os.path.join(args.save_model_path, 'latest_dice_loss.pth'))

        if epoch % args.validation_step == 0 and epoch != 0:
            precision, miou = val(args, model, dataloader_val)
            if miou > max_miou:
                max_miou = miou
                import os 
                os.makedirs(args.save_model_path, exist_ok=True)
                torch.save(model.module.state_dict(),
                           os.path.join(args.save_model_path, 'best_dice_loss.pth'))
            writer.add_scalar('epoch/precision_val', precision, epoch)
            writer.add_scalar('epoch/miou val', miou, epoch)

In [10]:
def main(params):
    # basic parameters
    parser = argparse.ArgumentParser()
    parser.add_argument('--num_epochs', type=int, default=300, help='Number of epochs to train for')
    parser.add_argument('--epoch_start_i', type=int, default=0, help='Start counting epochs from this number')
    parser.add_argument('--checkpoint_step', type=int, default=10, help='How often to save checkpoints (epochs)')
    parser.add_argument('--validation_step', type=int, default=10, help='How often to perform validation (epochs)')
    parser.add_argument('--dataset', type=str, default="Cityscapes", help='Dataset you are using.')
    parser.add_argument('--crop_height', type=int, default=720, help='Height of cropped/resized input image to network')
    parser.add_argument('--crop_width', type=int, default=960, help='Width of cropped/resized input image to network')
    parser.add_argument('--batch_size', type=int, default=32, help='Number of images in each batch')
    parser.add_argument("--iter-size", type=int, default=1, help="Accumulate gradients for ITER_SIZE iterations.")
    parser.add_argument('--context_path', type=str, default="resnet101",
                        help='The context path model you are using, resnet18, resnet101.')
    parser.add_argument('--learning_rate', type=float, default=0.01, help='learning rate used for train')
    parser.add_argument('--data', type=str, default='', help='path of training data')
    parser.add_argument("--data-list", type=str, default='/gdrive/MyDrive/data/Cityscapes/train.txt', help="Path to the file listing the images in the source dataset.")
    parser.add_argument("--data-list-val", type=str, default='/gdrive/MyDrive/data/Cityscapes/val.txt', help="Path to the file listing the image in the test subset.")
    parser.add_argument('--num_workers', type=int, default=4, help='num of workers')
    parser.add_argument('--num_classes', type=int, default=32, help='num of object classes (with void)')
    parser.add_argument("--num-steps", type=int, default=250000, help="Number of training steps.")
    parser.add_argument('--cuda', type=str, default='0', help='GPU ids used for training')
    parser.add_argument('--use_gpu', type=bool, default=True, help='whether to user gpu for training')
    parser.add_argument('--pretrained_model_path', type=str, default=None, help='path to pretrained model')
    parser.add_argument('--save_model_path', type=str, default=None, help='path to save model')
    parser.add_argument('--optimizer', type=str, default='rmsprop', help='optimizer, support rmsprop, sgd, adam')
    parser.add_argument('--loss', type=str, default='crossentropy', help='loss function, dice or crossentropy')
    parser.add_argument("--random-scale", action="store_true", help="Whether to randomly scale the inputs during the training.")
    parser.add_argument("--random-mirror", action="store_true", help="Whether to randomly mirror the inputs during the training.")
    parser.add_argument("--set-type", type=str, default='train', help="choose adaptation set.")

    args = parser.parse_args(params)

    input_size = (int(args.crop_height), int(args.crop_width))
    img_mean = np.array((104.00698793, 116.66876762, 122.67891434), dtype=np.float32)
    #img_mean=(128, 128, 128)

    # create dataset and dataloader
    train_path = [os.path.join(args.data, 'train'), os.path.join(args.data, 'val')]
    train_label_path = [os.path.join(args.data, 'train_labels'), os.path.join(args.data, 'val_labels')]
    test_path = os.path.join(args.data, 'test')
    test_label_path = os.path.join(args.data, 'test_labels')
    #csv_path = os.path.join(args.data, 'class_dict.csv')
    train_dataset = cityscapesDataSet(train_path, args.data_list,
                    crop_size=input_size,
                    scale=args.random_scale, mirror=args.random_mirror, 
                    mean=img_mean)
    print(f'train_dataset: {len(train_dataset)}')
    
    val_dataset = cityscapesDataSet(test_path, args.data_list_val,
                  crop_size=input_size,
                  scale=False, mirror=args.random_mirror, 
                  mean=img_mean)
    print(f'val_dataset: {len(val_dataset)}')
    
    # Define dataloaders
    dataloader_train = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True, num_workers=args.num_workers, pin_memory=True)
    
    dataloader_val = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers, pin_memory=True)
    
    # build model
    os.environ['CUDA_VISIBLE_DEVICES'] = args.cuda
    model = BiSeNet(args.num_classes, args.context_path)
    if torch.cuda.is_available() and args.use_gpu:
        model = torch.nn.DataParallel(model).cuda()

    # build optimizer
    if args.optimizer == 'rmsprop':
        optimizer = torch.optim.RMSprop(model.parameters(), args.learning_rate)
    elif args.optimizer == 'sgd':
        optimizer = torch.optim.SGD(model.parameters(), args.learning_rate, momentum=0.9, weight_decay=1e-4)
    elif args.optimizer == 'adam':
        optimizer = torch.optim.Adam(model.parameters(), args.learning_rate)
    else:  # rmsprop
        print('not supported optimizer \n')
        return None

    # load pretrained model if exists
    if args.pretrained_model_path is not None:
        print('load model from %s ...' % args.pretrained_model_path)
        model.module.load_state_dict(torch.load(args.pretrained_model_path))
        print('Done!')

    # train
    train(args, model, optimizer, dataloader_train, dataloader_val)

    # val(args, model, dataloader_val, csv_path)

In [11]:
if __name__ == '__main__':
    params = [
        '--num_epochs', '50',
        '--learning_rate', '2.5e-2',
        '--data', '/gdrive/MyDrive/data/Cityscapes',
        '--num_workers', '4',
        '--num_classes', '19',
        '--cuda', '0',
        '--batch_size', '5',
        '--save_model_path', '/gdrive/MyDrive/Project_AML/Models/checkpoints_101_adam',
        '--context_path', 'resnet101',  # set resnet18 or resnet101, only support resnet18 and resnet101
        '--optimizer', 'adam',

    ]
    main(params)

train_dataset: 10
val_dataset: 10


Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


  0%|          | 0.00/44.7M [00:00<?, ?B/s]

Downloading: "https://download.pytorch.org/models/resnet101-63fe2227.pth" to /root/.cache/torch/hub/checkpoints/resnet101-63fe2227.pth


  0%|          | 0.00/171M [00:00<?, ?B/s]

epoch 0, lr 0.025000:   0%|          | 0/10 [00:00<?, ?it/s]

image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B5C99990>
image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B5CB8610>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B5CC4E10>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B5CA2A50>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B5C99990>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B5CDE4D0>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B5CB1710>
image as array: [[[ 88. 124.   0.]
  [113. 143.  13.]
  [139. 168.  87.]
  ...
  [212. 237. 242.]
  [217. 235. 238.]
  [129. 153. 157.]]

 [[  5.  15.   4.]
  [ 13.  26.  14.]
  [ 45.  94.  60.]
  ...
  [212. 238. 242.]
  [217. 235. 238.]
  [131. 159. 163.]]

 [[ 26.  96.  24.]
  [ 81. 131.  72.]
  [125. 160. 117.]
  ...
  [212. 238. 242.]
  [217. 235. 239.]
  [132. 164. 

epoch 0, lr 0.025000:  50%|█████     | 5/10 [00:20<00:20,  4.01s/it, loss=9.809696]

data: tensor([[[[-1.0401e+02, -9.1007e+01, -1.7007e+01,  ...,  1.3799e+02,
            1.3399e+02,  5.2993e+01],
          [-1.0001e+02, -9.0007e+01, -4.4007e+01,  ...,  1.3799e+02,
            1.3399e+02,  5.8993e+01],
          [-8.0007e+01, -3.2007e+01,  1.2993e+01,  ...,  1.3799e+02,
            1.3499e+02,  6.3993e+01],
          ...,
          [-2.3007e+01, -2.6007e+01, -2.7007e+01,  ..., -4.8007e+01,
           -3.6007e+01, -2.5007e+01],
          [-2.3007e+01, -2.6007e+01, -2.7007e+01,  ..., -4.8007e+01,
           -4.8007e+01, -3.4007e+01],
          [-2.3007e+01, -2.6007e+01, -2.7007e+01,  ..., -4.8007e+01,
           -4.8007e+01, -4.8007e+01]],

         [[ 7.3312e+00,  2.6331e+01,  5.1331e+01,  ...,  1.2033e+02,
            1.1833e+02,  3.6331e+01],
          [-1.0167e+02, -9.0669e+01, -2.2669e+01,  ...,  1.2133e+02,
            1.1833e+02,  4.2331e+01],
          [-2.0669e+01,  1.4331e+01,  4.3331e+01,  ...,  1.2133e+02,
            1.1833e+02,  4.7331e+01],
          ...,

epoch 0, lr 0.025000: 100%|██████████| 10/10 [00:29<00:00,  2.91s/it, loss=8.572090]


loss for train : 9.190893


epoch 1, lr 0.024550:   0%|          | 0/10 [00:00<?, ?it/s]

image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B0796ED0>
image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B079AC10>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B5CCBF90>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07AC510>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B5CCBF90>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07B0250>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B079AC10>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B5CB2F50>
image as array: [[[42. 58. 33.]
  [33. 45. 25.]
  [28. 38. 21.]
  ...
  [22. 28. 25.]
  [18. 21. 19.]
  [13. 19. 17.]]

 [[35. 51. 27.]
  [28. 40. 23.]
  [30. 44. 26.]
  ...
  [21. 28. 25.]
  [18. 22. 20.]
  [13. 20. 18.]]

 [[30. 41. 23.]
  [28. 37. 23.]
  [33. 47. 29.]
  ...
  [21. 28. 25.

epoch 1, lr 0.024550:  50%|█████     | 5/10 [00:11<00:11,  2.22s/it, loss=8.519855]

data: tensor([[[[ -77.0070,  -76.0070,  -77.0070,  ...,  -69.0070,  -72.0070,
            -72.0070],
          [ -77.0070,  -76.0070,  -77.0070,  ...,  -71.0070,  -71.0070,
            -70.0070],
          [ -78.0070,  -77.0070,  -78.0070,  ...,  -73.0070,  -70.0070,
            -69.0070],
          ...,
          [ -34.0070,  -34.0070,  -31.0070,  ...,  -53.0070,  -51.0070,
            -50.0070],
          [ -35.0070,  -34.0070,  -31.0070,  ...,  -57.0070,  -56.0070,
            -55.0070],
          [ -35.0070,  -34.0070,  -31.0070,  ...,  -58.0070,  -57.0070,
            -56.0070]],

         [[ -82.6688,  -82.6688,  -79.6688,  ...,  -71.6688,  -74.6688,
            -74.6688],
          [ -83.6688,  -83.6688,  -81.6688,  ...,  -73.6688,  -74.6688,
            -72.6688],
          [ -84.6688,  -83.6688,  -82.6688,  ...,  -73.6688,  -71.6688,
            -70.6688],
          ...,
          [ -24.6688,  -24.6688,  -22.6688,  ...,  -50.6688,  -48.6688,
            -47.6688],
          [ 

epoch 1, lr 0.024550: 100%|██████████| 10/10 [00:20<00:00,  2.03s/it, loss=7.083848]


loss for train : 7.801851


epoch 2, lr 0.024098:   0%|          | 0/10 [00:00<?, ?it/s]

image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B0790910>
image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B0793590>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B56C6210>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07A8A10>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B56C6210>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07A8690>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B5CB2F50>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B5CB2F50>
image as array: [[[ 75. 101.  88.]
  [ 91. 114. 104.]
  [104. 127. 119.]
  ...
  [ 80. 100.  82.]
  [ 81. 101.  82.]
  [ 81. 100.  80.]]

 [[ 61.  85.  72.]
  [ 76. 102.  90.]
  [ 93. 118. 107.]
  ...
  [ 81. 101.  82.]
  [ 82. 101.  82.]
  [ 81. 101.  81.]]

 [[ 52.  74.  62.]
  [ 61.  87. 

epoch 2, lr 0.024098:  50%|█████     | 5/10 [00:11<00:11,  2.22s/it, loss=7.047044]

data: tensor([[[[-1.6007e+01, -6.9885e-03,  1.4993e+01,  ..., -2.2007e+01,
           -2.2007e+01, -2.4007e+01],
          [-3.2007e+01, -1.4007e+01,  2.9930e+00,  ..., -2.2007e+01,
           -2.2007e+01, -2.3007e+01],
          [-4.2007e+01, -3.1007e+01, -1.1007e+01,  ..., -2.2007e+01,
           -2.1007e+01, -2.1007e+01],
          ...,
          [-8.0007e+01, -8.0007e+01, -8.0007e+01,  ..., -5.4007e+01,
           -5.3007e+01, -5.2007e+01],
          [-8.0007e+01, -8.0007e+01, -8.0007e+01,  ..., -5.8007e+01,
           -5.6007e+01, -5.5007e+01],
          [-8.0007e+01, -8.0007e+01, -8.0007e+01,  ..., -6.3007e+01,
           -6.2007e+01, -6.0007e+01]],

         [[-1.5669e+01, -2.6688e+00,  1.0331e+01,  ..., -1.6669e+01,
           -1.5669e+01, -1.6669e+01],
          [-3.1669e+01, -1.4669e+01,  1.3312e+00,  ..., -1.5669e+01,
           -1.5669e+01, -1.5669e+01],
          [-4.2669e+01, -2.9669e+01, -1.1669e+01,  ..., -1.4669e+01,
           -1.3669e+01, -1.3669e+01],
          ...,

epoch 2, lr 0.024098: 100%|██████████| 10/10 [00:19<00:00,  1.96s/it, loss=6.245469]


loss for train : 6.646256


epoch 3, lr 0.023646:   0%|          | 0/10 [00:00<?, ?it/s]

image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B574CD10>
image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B574CD10>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B56CD290>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07ABD90>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B56CD290>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07AAAD0>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B574CD10>
image as array: [[[ 75. 101.  88.]
  [ 91. 114. 104.]
  [104. 127. 119.]
  ...
  [ 80. 100.  82.]
  [ 81. 101.  82.]
  [ 81. 100.  80.]]

 [[ 61.  85.  72.]
  [ 76. 102.  90.]
  [ 93. 118. 107.]
  ...
  [ 81. 101.  82.]
  [ 82. 101.  82.]
  [ 81. 101.  81.]]

 [[ 52.  74.  62.]
  [ 61.  87.  73.]
  [ 79. 105.  93.]
  ...
  [ 83. 102.  82.]
  [ 83. 103.  83.]
  [ 83. 103. 

epoch 3, lr 0.023646:  50%|█████     | 5/10 [00:10<00:10,  2.16s/it, loss=4.937806]

data: tensor([[[[-1.6007e+01, -6.9885e-03,  1.4993e+01,  ..., -2.2007e+01,
           -2.2007e+01, -2.4007e+01],
          [-3.2007e+01, -1.4007e+01,  2.9930e+00,  ..., -2.2007e+01,
           -2.2007e+01, -2.3007e+01],
          [-4.2007e+01, -3.1007e+01, -1.1007e+01,  ..., -2.2007e+01,
           -2.1007e+01, -2.1007e+01],
          ...,
          [-8.0007e+01, -8.0007e+01, -8.0007e+01,  ..., -5.4007e+01,
           -5.3007e+01, -5.2007e+01],
          [-8.0007e+01, -8.0007e+01, -8.0007e+01,  ..., -5.8007e+01,
           -5.6007e+01, -5.5007e+01],
          [-8.0007e+01, -8.0007e+01, -8.0007e+01,  ..., -6.3007e+01,
           -6.2007e+01, -6.0007e+01]],

         [[-1.5669e+01, -2.6688e+00,  1.0331e+01,  ..., -1.6669e+01,
           -1.5669e+01, -1.6669e+01],
          [-3.1669e+01, -1.4669e+01,  1.3312e+00,  ..., -1.5669e+01,
           -1.5669e+01, -1.5669e+01],
          [-4.2669e+01, -2.9669e+01, -1.1669e+01,  ..., -1.4669e+01,
           -1.3669e+01, -1.3669e+01],
          ...,

epoch 3, lr 0.023646: 100%|██████████| 10/10 [00:19<00:00,  1.96s/it, loss=6.082055]


loss for train : 5.509930


epoch 4, lr 0.023193:   0%|          | 0/10 [00:00<?, ?it/s]

image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B0797ED0>
image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B07A2BD0>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B07B0E90>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07B0F90>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B07AF190>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07B91D0>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B5CB2F50>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B575C2D0>
image as array: [[[42. 58. 33.]
  [33. 45. 25.]
  [28. 38. 21.]
  ...
  [22. 28. 25.]
  [18. 21. 19.]
  [13. 19. 17.]]

 [[35. 51. 27.]
  [28. 40. 23.]
  [30. 44. 26.]
  ...
  [21. 28. 25.]
  [18. 22. 20.]
  [13. 20. 18.]]

 [[30. 41. 23.]
  [28. 37. 23.]
  [33. 47. 29.]
  ...
  [21. 28. 25.

epoch 4, lr 0.023193:  50%|█████     | 5/10 [00:10<00:10,  2.17s/it, loss=5.460419]

data: tensor([[[[ -61.0070,  -50.0070,  -43.0070,  ...,  -56.0070,  -45.0070,
            -42.0070],
          [ -68.0070,  -59.0070,  -49.0070,  ...,  -53.0070,  -44.0070,
            -44.0070],
          [ -70.0070,  -65.0070,  -52.0070,  ...,  -56.0070,  -48.0070,
            -47.0070],
          ...,
          [ -53.0070,  -52.0070,  -52.0070,  ...,  -56.0070,  -57.0070,
            -57.0070],
          [ -53.0070,  -52.0070,  -52.0070,  ...,  -58.0070,  -57.0070,
            -58.0070],
          [ -53.0070,  -52.0070,  -52.0070,  ...,  -56.0070,  -57.0070,
            -59.0070]],

         [[ -59.6688,  -49.6688,  -42.6688,  ...,  -57.6688,  -46.6688,
            -41.6688],
          [ -67.6688,  -59.6688,  -49.6688,  ...,  -54.6688,  -46.6688,
            -44.6688],
          [ -68.6688,  -64.6688,  -52.6688,  ...,  -55.6688,  -50.6688,
            -47.6688],
          ...,
          [ -56.6688,  -56.6688,  -56.6688,  ...,  -59.6688,  -60.6688,
            -60.6688],
          [ 

epoch 4, lr 0.023193: 100%|██████████| 10/10 [00:19<00:00,  1.97s/it, loss=5.583094]


loss for train : 5.521756


epoch 5, lr 0.022738:   0%|          | 0/10 [00:00<?, ?it/s]

image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B07A2710>
image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B578BF90>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B56C6C90>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07B6810>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B56C6C90>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B5CDEC50>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B5CB2F50>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B578BF90>
image as array: [[[134. 132.   0.]
  [152. 164.   1.]
  [174. 191.  55.]
  ...
  [  6.  16.  13.]
  [  9.  30.  27.]
  [ 27.  40.  37.]]

 [[ 16.  44.   1.]
  [ 62. 122.  11.]
  [138. 174.  51.]
  ...
  [  6.  17.  13.]
  [ 10.  30.  27.]
  [ 27.  39.  37.]]

 [[ 89. 125.   5.]
  [119. 149. 

epoch 5, lr 0.022738:  50%|█████     | 5/10 [00:10<00:10,  2.20s/it, loss=6.035416]

data: tensor([[[[-5.5007e+01, -4.0007e+01, -2.4007e+01,  ...,  5.5993e+01,
           -4.1007e+01, -2.0070e+00],
          [-8.9007e+01, -6.1007e+01, -3.5007e+01,  ...,  5.5993e+01,
           -4.1007e+01, -1.0070e+00],
          [-1.0301e+02, -7.9007e+01, -4.5007e+01,  ...,  5.4993e+01,
           -4.1007e+01,  9.9301e-01],
          ...,
          [-3.8007e+01, -4.0007e+01, -3.9007e+01,  ..., -3.0070e+00,
           -2.0007e+01, -3.8007e+01],
          [-3.8007e+01, -4.0007e+01, -3.9007e+01,  ...,  9.9301e-01,
           -1.0070e+00, -2.7007e+01],
          [-3.8007e+01, -4.0007e+01, -3.9007e+01,  ...,  1.9930e+00,
            1.9930e+00,  9.9301e-01]],

         [[-3.6688e+00, -6.6877e-01,  3.3312e+00,  ...,  5.2331e+01,
           -4.8669e+01,  2.3312e+00],
          [-6.6688e+00, -6.6877e-01,  4.3312e+00,  ...,  5.1331e+01,
           -4.3669e+01,  5.3312e+00],
          [-1.0669e+01, -2.6688e+00,  3.3312e+00,  ...,  5.0331e+01,
           -3.8669e+01,  8.3312e+00],
          ...,

epoch 5, lr 0.022738: 100%|██████████| 10/10 [00:19<00:00,  1.98s/it, loss=4.445143]


loss for train : 5.240279


epoch 6, lr 0.022283:   0%|          | 0/10 [00:00<?, ?it/s]

image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B079CA10>
image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B07A0750>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B56DC050>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07B5AD0>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B578BF50>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07B3810>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B079CA10>
image as array: [[[105. 113.  49.]
  [105. 116.  64.]
  [106. 120.  80.]
  ...
  [ 32. 169. 160.]
  [ 22.  68.  63.]
  [  0. 119. 102.]]

 [[ 83. 110.  15.]
  [ 92. 116.  43.]
  [ 99. 121.  69.]
  ...
  [ 34. 168. 160.]
  [ 23.  73.  63.]
  [  0. 122. 103.]]

 [[ 63. 106.   1.]
  [ 77. 114.  25.]
  [ 90. 120.  59.]
  ...
  [ 36. 167. 159.]
  [ 24.  78.  63.]
  [  0. 125. 

epoch 6, lr 0.022283:  50%|█████     | 5/10 [00:11<00:11,  2.24s/it, loss=5.275901]

data: tensor([[[[-5.5007e+01, -4.0007e+01, -2.4007e+01,  ...,  5.5993e+01,
           -4.1007e+01, -2.0070e+00],
          [-8.9007e+01, -6.1007e+01, -3.5007e+01,  ...,  5.5993e+01,
           -4.1007e+01, -1.0070e+00],
          [-1.0301e+02, -7.9007e+01, -4.5007e+01,  ...,  5.4993e+01,
           -4.1007e+01,  9.9301e-01],
          ...,
          [-3.8007e+01, -4.0007e+01, -3.9007e+01,  ..., -3.0070e+00,
           -2.0007e+01, -3.8007e+01],
          [-3.8007e+01, -4.0007e+01, -3.9007e+01,  ...,  9.9301e-01,
           -1.0070e+00, -2.7007e+01],
          [-3.8007e+01, -4.0007e+01, -3.9007e+01,  ...,  1.9930e+00,
            1.9930e+00,  9.9301e-01]],

         [[-3.6688e+00, -6.6877e-01,  3.3312e+00,  ...,  5.2331e+01,
           -4.8669e+01,  2.3312e+00],
          [-6.6688e+00, -6.6877e-01,  4.3312e+00,  ...,  5.1331e+01,
           -4.3669e+01,  5.3312e+00],
          [-1.0669e+01, -2.6688e+00,  3.3312e+00,  ...,  5.0331e+01,
           -3.8669e+01,  8.3312e+00],
          ...,

epoch 6, lr 0.022283: 100%|██████████| 10/10 [00:19<00:00,  1.99s/it, loss=4.539284]


loss for train : 4.907593


epoch 7, lr 0.021827:   0%|          | 0/10 [00:00<?, ?it/s]

image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B079EAD0>
image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B079DD90>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B57A6D90>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07B7E50>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B5CE8690>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B07B5B90>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B079DD90>
image as array: [[[ 78. 100.  87.]
  [ 80. 102.  90.]
  [ 79. 101.  88.]
  ...
  [ 20.  30.  24.]
  [ 22.  33.  26.]
  [ 22.  35.  25.]]

 [[ 79. 100.  87.]
  [ 81. 102.  90.]
  [ 79. 101.  88.]
  ...
  [ 18.  28.  22.]
  [ 19.  30.  23.]
  [ 23.  37.  27.]]

 [[ 79. 100.  87.]
  [ 81. 102.  89.]
  [ 79. 101.  89.]
  ...
  [ 16.  27.  20.]
  [ 18.  31.  22.]
  [ 27.  41. 

epoch 7, lr 0.021827:  50%|█████     | 5/10 [00:11<00:11,  2.21s/it, loss=4.370048]

data: tensor([[[[-1.7007e+01, -1.4007e+01, -1.6007e+01,  ..., -8.0007e+01,
           -7.8007e+01, -7.9007e+01],
          [-1.7007e+01, -1.4007e+01, -1.6007e+01,  ..., -8.2007e+01,
           -8.1007e+01, -7.7007e+01],
          [-1.7007e+01, -1.5007e+01, -1.5007e+01,  ..., -8.4007e+01,
           -8.2007e+01, -7.4007e+01],
          ...,
          [-5.2007e+01, -5.1007e+01, -5.1007e+01,  ..., -5.6007e+01,
           -5.5007e+01, -5.3007e+01],
          [-5.2007e+01, -5.1007e+01, -5.1007e+01,  ..., -5.9007e+01,
           -5.9007e+01, -5.7007e+01],
          [-5.2007e+01, -5.1007e+01, -5.1007e+01,  ..., -6.0007e+01,
           -6.0007e+01, -6.0007e+01]],

         [[-1.6669e+01, -1.4669e+01, -1.5669e+01,  ..., -8.6669e+01,
           -8.3669e+01, -8.1669e+01],
          [-1.6669e+01, -1.4669e+01, -1.5669e+01,  ..., -8.8669e+01,
           -8.6669e+01, -7.9669e+01],
          [-1.6669e+01, -1.4669e+01, -1.5669e+01,  ..., -8.9669e+01,
           -8.5669e+01, -7.5669e+01],
          ...,

epoch 7, lr 0.021827: 100%|██████████| 10/10 [00:19<00:00,  1.99s/it, loss=4.081372]


loss for train : 4.225710


epoch 8, lr 0.021369:   0%|          | 0/10 [00:00<?, ?it/s]

image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B1FA0D90>
image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B1FADC10>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B5CDE5D0>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B1FBAE90>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B1FA0D90>
image as array: [[[ 78. 100.  87.]
  [ 80. 102.  90.]
  [ 79. 101.  88.]
  ...
  [ 20.  30.  24.]
  [ 22.  33.  26.]
  [ 22.  35.  25.]]

 [[ 79. 100.  87.]
  [ 81. 102.  90.]
  [ 79. 101.  88.]
  ...
  [ 18.  28.  22.]
  [ 19.  30.  23.]
  [ 23.  37.  27.]]

 [[ 79. 100.  87.]
  [ 81. 102.  89.]
  [ 79. 101.  89.]
  ...
  [ 16.  27.  20.]
  [ 18.  31.  22.]
  [ 27.  41.  30.]]

 ...

 [[ 47.  60.  52.]
  [ 48.  63.  53.]
  [ 47.  61.  53.]
  ...
  [ 43.  58.  48.]
  [ 46.  59.  49.]
  [ 47.  59.  51.]]

 [[ 48.  61.  52.]
  [ 48.  63.  53.]
  [ 47.  61

epoch 8, lr 0.021369:  50%|█████     | 5/10 [00:11<00:11,  2.24s/it, loss=4.498821]

data: tensor([[[[ -77.0070,  -76.0070,  -77.0070,  ...,  -69.0070,  -72.0070,
            -72.0070],
          [ -77.0070,  -76.0070,  -77.0070,  ...,  -71.0070,  -71.0070,
            -70.0070],
          [ -78.0070,  -77.0070,  -78.0070,  ...,  -73.0070,  -70.0070,
            -69.0070],
          ...,
          [ -34.0070,  -34.0070,  -31.0070,  ...,  -53.0070,  -51.0070,
            -50.0070],
          [ -35.0070,  -34.0070,  -31.0070,  ...,  -57.0070,  -56.0070,
            -55.0070],
          [ -35.0070,  -34.0070,  -31.0070,  ...,  -58.0070,  -57.0070,
            -56.0070]],

         [[ -82.6688,  -82.6688,  -79.6688,  ...,  -71.6688,  -74.6688,
            -74.6688],
          [ -83.6688,  -83.6688,  -81.6688,  ...,  -73.6688,  -74.6688,
            -72.6688],
          [ -84.6688,  -83.6688,  -82.6688,  ...,  -73.6688,  -71.6688,
            -70.6688],
          ...,
          [ -24.6688,  -24.6688,  -22.6688,  ...,  -50.6688,  -48.6688,
            -47.6688],
          [ 

epoch 8, lr 0.021369: 100%|██████████| 10/10 [00:19<00:00,  2.00s/it, loss=3.530629]


loss for train : 4.014725


epoch 9, lr 0.020911:   0%|          | 0/10 [00:00<?, ?it/s]

image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B1FAEC90>
image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B1FAD550>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B5CDEF50>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B1F452D0>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B5CDEF50>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B1F40650>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B5CB2F50>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B5CB2F50>
image as array: [[[36. 57. 43.]
  [43. 67. 54.]
  [47. 74. 61.]
  ...
  [42. 59. 48.]
  [51. 70. 59.]
  [58. 75. 62.]]

 [[31. 49. 36.]
  [37. 57. 45.]
  [47. 67. 55.]
  ...
  [45. 62. 51.]
  [51. 70. 60.]
  [53. 72. 60.]]

 [[29. 48. 34.]
  [34. 52. 39.]
  [48. 64. 52.]
  ...
  [45. 61. 48.

epoch 9, lr 0.020911:  50%|█████     | 5/10 [00:11<00:11,  2.25s/it, loss=4.167357]

data: tensor([[[[-1.0401e+02, -1.0301e+02, -4.9007e+01,  ..., -9.1007e+01,
           -7.7007e+01, -6.7007e+01],
          [-1.0301e+02, -9.3007e+01, -5.3007e+01,  ..., -9.1007e+01,
           -7.7007e+01, -6.7007e+01],
          [-9.9007e+01, -4.3007e+01,  2.6993e+01,  ..., -9.0007e+01,
           -7.7007e+01, -6.7007e+01],
          ...,
          [-3.4007e+01, -3.5007e+01, -3.3007e+01,  ..., -4.7007e+01,
           -4.1007e+01, -3.6007e+01],
          [-3.4007e+01, -3.5007e+01, -3.3007e+01,  ..., -5.0007e+01,
           -4.9007e+01, -4.2007e+01],
          [-3.4007e+01, -3.5007e+01, -3.3007e+01,  ..., -5.1007e+01,
           -5.1007e+01, -5.0007e+01]],

         [[ 1.5331e+01,  4.7331e+01,  7.4331e+01,  ..., -1.0067e+02,
           -8.6669e+01, -7.6669e+01],
          [-7.2669e+01,  5.3312e+00,  5.7331e+01,  ..., -9.9669e+01,
           -8.6669e+01, -7.7669e+01],
          [ 8.3312e+00,  3.2331e+01,  6.8331e+01,  ..., -9.9669e+01,
           -8.6669e+01, -7.7669e+01],
          ...,

epoch 9, lr 0.020911: 100%|██████████| 10/10 [00:20<00:00,  2.00s/it, loss=3.600603]


loss for train : 3.883980


epoch 10, lr 0.020451:   0%|          | 0/10 [00:00<?, ?it/s]

image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B1FBBE50>
image before resize: <PIL.Image.Image image mode=RGB size=2048x1024 at 0x7F90B1FBBB90>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B5709750>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B5709050>
image after resize: <PIL.Image.Image image mode=RGB size=720x960 at 0x7F90B575CE10>
label before resize: <PIL.PngImagePlugin.PngImageFile image mode=L size=2048x1024 at 0x7F90B575CBD0>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B1FBBE50>
label after resize: <PIL.Image.Image image mode=L size=720x960 at 0x7F90B1FBBB90>
image as array: [[[36. 57. 43.]
  [43. 67. 54.]
  [47. 74. 61.]
  ...
  [42. 59. 48.]
  [51. 70. 59.]
  [58. 75. 62.]]

 [[31. 49. 36.]
  [37. 57. 45.]
  [47. 67. 55.]
  ...
  [45. 62. 51.]
  [51. 70. 60.]
  [53. 72. 60.]]

 [[29. 48. 34.]
  [34. 52. 39.]
  [48. 64. 52.]
  ...
  [45. 61. 48.

epoch 10, lr 0.020451:  50%|█████     | 5/10 [00:11<00:11,  2.24s/it, loss=3.958021]

data: tensor([[[[-6.1007e+01, -5.0007e+01, -4.3007e+01,  ..., -5.6007e+01,
           -4.5007e+01, -4.2007e+01],
          [-6.8007e+01, -5.9007e+01, -4.9007e+01,  ..., -5.3007e+01,
           -4.4007e+01, -4.4007e+01],
          [-7.0007e+01, -6.5007e+01, -5.2007e+01,  ..., -5.6007e+01,
           -4.8007e+01, -4.7007e+01],
          ...,
          [-5.3007e+01, -5.2007e+01, -5.2007e+01,  ..., -5.6007e+01,
           -5.7007e+01, -5.7007e+01],
          [-5.3007e+01, -5.2007e+01, -5.2007e+01,  ..., -5.8007e+01,
           -5.7007e+01, -5.8007e+01],
          [-5.3007e+01, -5.2007e+01, -5.2007e+01,  ..., -5.6007e+01,
           -5.7007e+01, -5.9007e+01]],

         [[-5.9669e+01, -4.9669e+01, -4.2669e+01,  ..., -5.7669e+01,
           -4.6669e+01, -4.1669e+01],
          [-6.7669e+01, -5.9669e+01, -4.9669e+01,  ..., -5.4669e+01,
           -4.6669e+01, -4.4669e+01],
          [-6.8669e+01, -6.4669e+01, -5.2669e+01,  ..., -5.5669e+01,
           -5.0669e+01, -4.7669e+01],
          ...,

epoch 10, lr 0.020451: 100%|██████████| 10/10 [00:20<00:00,  2.00s/it, loss=3.646266]


loss for train : 3.802144
start val!


FileNotFoundError: ignored